Setup Continuous Integration service.
ncs-jss/Q_hub pull request #4
Opened 2017-01-02 12:15 UTC by dhruvhacks

All bugs resolved.

2017-01-02 17:41 UTC, RishabhJain2018 requested changes
Please add email notification on success as well as on failure.

2017-01-03 08:21 UTC, dhruvhacks reviewed
Okay sir,
New commit created.

2017-01-03 09:27 UTC, RishabhJain2018 commented on .travis.yml
> +    on_failure: always
Please leave a blank line here.

2017-01-03 13:11 UTC, RishabhJain2018 commented
@dhruvhacks Always mention the **issue number** in the PR like `#100.` Git then automatically relates the PR with the issue.

2017-01-03 18:01 UTC, dhruvhacks commented on .travis.yml
> +    on_failure: always
okay sir,

2017-01-10 17:34 UTC, RishabhJain2018 commented on .travis.yml
> +    on_failure: always
@dhruvhacks Please leave a line here and then commit again.

2017-01-10 19:14 UTC, dhruvhacks commented on .travis.yml
> +    on_failure: always
Sorry sir, Added a new  line at the end of file.

2017-01-13 13:21 UTC, RishabhJain2018 commented
@dhruvhacks @prakharchoudhary also add a `.coveragerc` and `.coveralls`.yml file.

2017-01-13 14:38 UTC, RishabhJain2018 commented
The `.coveralls.yml` and `.coveragerc` files will be added in the next issue.

2017-01-13 14:39 UTC, merged